/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutFooter: typeof import('./src/components/Layout/LayoutFooter.vue')['default']
    LayoutNavTop: typeof import('./src/components/Layout/LayoutNavTop.vue')['default']
    LayoutNavTopSearch: typeof import('./src/components/Layout/LayoutNavTopSearch.vue')['default']
    LayoutNavTopUserHome: typeof import('./src/components/Layout/LayoutNavTopUserHome.vue')['default']
    LayoutSearch: typeof import('./src/components/Layout/LayoutSearch.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    NavTop: typeof import('./src/components/Layout/LayoutNavTop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoCard: typeof import('./src/components/Video/VideoCard.vue')['default']
  }
}
