/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/user/Avatar.vue')['default']
    ContributorGrid: typeof import('./src/components/Leaderboard/ContributorGrid.vue')['default']
    ContributorLogo: typeof import('./src/components/Leaderboard/ContributorLogo.vue')['default']
    ContributorLogoTop: typeof import('./src/components/Leaderboard/ContributorLogoTop.vue')['default']
    ContributorRank: typeof import('./src/components/Leaderboard/ContributorRank.vue')['default']
    DarkModeSwitch: typeof import('./src/components/Layout/DarkModeSwitch.vue')['default']
    EditHistory: typeof import('./src/components/Leaderboard/EditHistory.vue')['default']
    EditHistoryGrid: typeof import('./src/components/Leaderboard/EditHistoryGrid.vue')['default']
    HListbox: typeof import('@headlessui/vue')['Listbox']
    HListboxButton: typeof import('@headlessui/vue')['ListboxButton']
    HListboxOption: typeof import('@headlessui/vue')['ListboxOption']
    HListboxOptions: typeof import('@headlessui/vue')['ListboxOptions']
    LayoutFooter: typeof import('./src/components/Layout/LayoutFooter.vue')['default']
    LayoutNavTop: typeof import('./src/components/Layout/LayoutNavTop.vue')['default']
    LayoutNavTopLink: typeof import('./src/components/Layout/LayoutNavTopLink.vue')['default']
    LayoutNavTopSearch: typeof import('./src/components/Layout/LayoutNavTopSearch.vue')['default']
    LayoutNavTopUserHome: typeof import('./src/components/Layout/LayoutNavTopUserHome.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    PlaylistCoverLink: typeof import('./src/components/Playlist/PlaylistCoverLink.vue')['default']
    PlaylistGrid: typeof import('./src/components/Playlist/PlaylistGrid.vue')['default']
    PlaylistGridTitle: typeof import('./src/components/Playlist/PlaylistGridTitle.vue')['default']
    PlaylistTitleLink: typeof import('./src/components/Playlist/PlaylistTitleLink.vue')['default']
    Popover: typeof import('./src/components/common/Popover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/common/Select.vue')['default']
    Tag: typeof import('./src/components/common/Tag.vue')['default']
    VideoCard: typeof import('./src/components/Video/VideoCard.vue')['default']
    VideoCover: typeof import('./src/components/Video/VideoCover.vue')['default']
    VideoListHome: typeof import('./src/components/Video/VideoListHome.vue')['default']
    VideoPagination: typeof import('./src/components/Video/VideoPagination.vue')['default']
    VideoSiteIcon: typeof import('./src/components/Video/VideoSiteIcon.vue')['default']
  }
}
