/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/user/Avatar.vue')['default']
    DarkModeSwitch: typeof import('./src/components/Layout/DarkModeSwitch.vue')['default']
    LayoutFooter: typeof import('./src/components/Layout/LayoutFooter.vue')['default']
    LayoutNavTop: typeof import('./src/components/Layout/LayoutNavTop.vue')['default']
    LayoutNavTopLink: typeof import('./src/components/Layout/LayoutNavTopLink.vue')['default']
    LayoutNavTopSearch: typeof import('./src/components/Layout/LayoutNavTopSearch.vue')['default']
    LayoutNavTopUserHome: typeof import('./src/components/Layout/LayoutNavTopUserHome.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoCard: typeof import('./src/components/Video/VideoCard.vue')['default']
    VideoCardSiteIcon: typeof import('./src/components/Video/VideoCardSiteIcon.vue')['default']
    VideoListHome: typeof import('./src/components/Video/VideoListHome.vue')['default']
    VideoPagination: typeof import('./src/components/Video/VideoPagination.vue')['default']
  }
}
